# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ohci_pci"
    "ehci_pci"
    "ahci"
    "firewire_ohci"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [
    "kvm-intel"
    "wl"
  ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  boot.initrd.luks.devices = {
    "root" = {
      device = "/dev/disk/by-uuid/3925c691-1684-4926-8c00-6da9e0c7680b";
      preLVM = false;
    };
    "home" = {
      device = "/dev/disk/by-uuid/82f7c05c-64b7-4e4d-b018-19f53ec418f3";
      preLVM = false;
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c18dd293-47a3-4bef-a920-30f0a8fac89b";
    fsType = "ext4";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/54ee8df9-129d-4934-907d-c38683b480cc";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8362-1BF4";
    fsType = "vfat";
  };

  swapDevices = [ ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
